### ISSUE TITLE
what is `#pragma pack` when should I use this in my C library?

### ISSUE THREAD

**Issue by boddumanohar** [merces/libpe#15]
Since I am new to C projects, I am having a doubt when should I use #pragma pack. In all the header files we have used `#pragma pack(push, <somenumber>` and `#pragma pack(pop)`

I've read this blog https://msdn.microsoft.com/en-us/library/2e70t5y1.aspx even still my doubt is not clarified. Can you please explain in simple terms 
1. When should I use this?
2. What if I dont use this?

Thanks,
Manohar.

**Comment by jweyrich** [comment]
`#pragma pack` is a directive used to tell the compiler how to align struct/class members in memory. The compiler uses a default alignment, which varies depending on the architecture and/or compilation flags. You can override the default alignment by using `#pragma pack`.

Let's say you have `typedef struct { char a; int b; } foo_t;`. According to the language definition, `sizeof char` MUST be 1, and `sizeof int` varies depending on the architecture/compiler combination. On 32-bit and 64-bit architectures, its natural size is 4 bytes, enough to contain values in the range specified by `INT_MIN` and `INT_MAX` as defined in the header `<limits.h>`.

So given that `sizeof char == 1` and `sizeof int == 4`, you'd expect `sizeof foo_t` to be `5`, right? We assume that the size of a struct should be equal to the the sum of the size of its members. But that's not always true. In fact, `sizeof foo_t` above will most likely be 8 instead of 5. This behavior is due to a memory padding the compiler added to the struct, inserted between the 2 members, `a` (1 byte) and `b` (4 bytes), so both members are aligned.

The processor can naturally access (read/write) memory aligned data, but non-aligned data requires extra CPU cycles in order to do memory shifting after reading it from memory and before writing it back to memory. As an example, x86 processors can naturally read/write 4 bytes. It will always read or write 4 bytes, even if you're willing to read or write 1 single byte in memory. So if a struct member is not aligned, and it wants to change its value, the processor spends these extra cycles. It's a tradeoff between performance and memory usage.

Now back to `#pragma pack` - The PE/COFF specification tells us exactly how its headers are laid out (in disk, or memory), so we have various scenarios like `foo_t` above, where members are not aligned, and we have to change the alignment it in order to read/write the values correctly.

I'd like to write an example, but someone already did it - and may have explained it better than me, so I suggest you to also read the following answer -
 https://stackoverflow.com/a/3318475/298054

Hope this helps!

**Comment by boddumanohar** [comment]
So when I use `#pragma pack` the size of the above struct will be 5. So we use this to selectively disable padding. And we need to do this here because PE specification tells us that there are no padding between data members. 

Clarifed. A thousand thanks for such a clear explanation :)
